"""initial

Revision ID: 6b02c6dba1a1
Revises: 
Create Date: 2026-01-25 11:59:42.981318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b02c6dba1a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_payment_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('supports_amount', sa.Boolean(), nullable=True),
    sa.Column('amount_parameter', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_payment_urls_id'), 'dynamic_payment_urls', ['id'], unique=False)
    op.create_index(op.f('ix_dynamic_payment_urls_is_active'), 'dynamic_payment_urls', ['is_active'], unique=False)
    op.create_table('working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('work_start', sa.String(length=5), nullable=True),
    sa.Column('work_end', sa.String(length=5), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_hours_day_of_week'), 'working_hours', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_working_hours_id'), 'working_hours', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_hours_id'), table_name='working_hours')
    op.drop_index(op.f('ix_working_hours_day_of_week'), table_name='working_hours')
    op.drop_table('working_hours')
    op.drop_index(op.f('ix_dynamic_payment_urls_is_active'), table_name='dynamic_payment_urls')
    op.drop_index(op.f('ix_dynamic_payment_urls_id'), table_name='dynamic_payment_urls')
    op.drop_table('dynamic_payment_urls')
    # ### end Alembic commands ###
