"""add_name

Revision ID: 9bd438a8d5c8
Revises: 6b02c6dba1a1
Create Date: 2026-01-25 12:02:17.390366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd438a8d5c8'
down_revision: Union[str, None] = '6b02c6dba1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_payment_urls', sa.Column('name', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_dynamic_payment_urls_name'), 'dynamic_payment_urls', ['name'], unique=False)
    op.drop_column('dynamic_payment_urls', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_payment_urls', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_dynamic_payment_urls_name'), table_name='dynamic_payment_urls')
    op.drop_column('dynamic_payment_urls', 'name')
    # ### end Alembic commands ###
